search:
  experiences_search:
    fields:
      - region^2
      - title
      - company.name^2
      - type^3
      - job_title^2
      - sections.subtitle^2
    analyzer: jieba_index
    type: most_fields

  
