version: '3.3'
services:
  es:
    image: docker.pkg.github.com/wendellliu/good-search-images/good-search-es:0.1 
    container_name: es01-dev
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - http.port=9200
      - transport.host=127.0.0.1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.allow-origin=http://127.0.0.1:1358"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true" 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.3.0
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
      SERVER_NAME: localhost
    depends_on:
      - es
    ports:
      - 5601:5601
  rabbitmq:
    hostname: good-search-rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.8.2-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@good-search-rabbitmq
