// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goodsearch.proto

package goodsearch

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetExperienceReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExperienceReq) Reset()         { *m = GetExperienceReq{} }
func (m *GetExperienceReq) String() string { return proto.CompactTextString(m) }
func (*GetExperienceReq) ProtoMessage()    {}
func (*GetExperienceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{0}
}

func (m *GetExperienceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExperienceReq.Unmarshal(m, b)
}
func (m *GetExperienceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExperienceReq.Marshal(b, m, deterministic)
}
func (m *GetExperienceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExperienceReq.Merge(m, src)
}
func (m *GetExperienceReq) XXX_Size() int {
	return xxx_messageInfo_GetExperienceReq.Size(m)
}
func (m *GetExperienceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExperienceReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetExperienceReq proto.InternalMessageInfo

func (m *GetExperienceReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetExperienceResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExperienceResp) Reset()         { *m = GetExperienceResp{} }
func (m *GetExperienceResp) String() string { return proto.CompactTextString(m) }
func (*GetExperienceResp) ProtoMessage()    {}
func (*GetExperienceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{1}
}

func (m *GetExperienceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExperienceResp.Unmarshal(m, b)
}
func (m *GetExperienceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExperienceResp.Marshal(b, m, deterministic)
}
func (m *GetExperienceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExperienceResp.Merge(m, src)
}
func (m *GetExperienceResp) XXX_Size() int {
	return xxx_messageInfo_GetExperienceResp.Size(m)
}
func (m *GetExperienceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExperienceResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetExperienceResp proto.InternalMessageInfo

func (m *GetExperienceResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetExperienceResp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*GetExperienceReq)(nil), "goodsearch.GetExperienceReq")
	proto.RegisterType((*GetExperienceResp)(nil), "goodsearch.GetExperienceResp")
}

func init() { proto.RegisterFile("goodsearch.proto", fileDescriptor_a44eebf31dd75a2c) }

var fileDescriptor_a44eebf31dd75a2c = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xcf, 0xcf, 0x4f,
	0x29, 0x4e, 0x4d, 0x2c, 0x4a, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x29, 0x71, 0x09, 0xb8, 0xa7, 0x96, 0xb8, 0x56, 0x14, 0xa4, 0x16, 0x65, 0xa6, 0xe6, 0x25,
	0xa7, 0x06, 0xa5, 0x16, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x31, 0x65, 0xa6, 0x28, 0x99, 0x73, 0x09, 0xa2, 0xa9, 0x29, 0x2e, 0x40, 0x57, 0x24, 0x24,
	0xc4, 0xc5, 0x52, 0x52, 0x59, 0x90, 0x2a, 0xc1, 0x04, 0x16, 0x01, 0xb3, 0x8d, 0x62, 0xb8, 0xb8,
	0xdc, 0xf3, 0xf3, 0x53, 0x82, 0xc1, 0x56, 0x09, 0xf9, 0x71, 0xf1, 0xa2, 0x18, 0x23, 0x24, 0xa3,
	0x87, 0xe4, 0x34, 0x74, 0x57, 0x48, 0xc9, 0xe2, 0x91, 0x2d, 0x2e, 0x50, 0x62, 0x48, 0x62, 0x03,
	0xfb, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x04, 0x37, 0x93, 0x32, 0xe1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoodSearchClient is the client API for GoodSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoodSearchClient interface {
	GetExperience(ctx context.Context, in *GetExperienceReq, opts ...grpc.CallOption) (*GetExperienceResp, error)
}

type goodSearchClient struct {
	cc *grpc.ClientConn
}

func NewGoodSearchClient(cc *grpc.ClientConn) GoodSearchClient {
	return &goodSearchClient{cc}
}

func (c *goodSearchClient) GetExperience(ctx context.Context, in *GetExperienceReq, opts ...grpc.CallOption) (*GetExperienceResp, error) {
	out := new(GetExperienceResp)
	err := c.cc.Invoke(ctx, "/goodsearch.GoodSearch/GetExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodSearchServer is the server API for GoodSearch service.
type GoodSearchServer interface {
	GetExperience(context.Context, *GetExperienceReq) (*GetExperienceResp, error)
}

// UnimplementedGoodSearchServer can be embedded to have forward compatible implementations.
type UnimplementedGoodSearchServer struct {
}

func (*UnimplementedGoodSearchServer) GetExperience(ctx context.Context, req *GetExperienceReq) (*GetExperienceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExperience not implemented")
}

func RegisterGoodSearchServer(s *grpc.Server, srv GoodSearchServer) {
	s.RegisterService(&_GoodSearch_serviceDesc, srv)
}

func _GoodSearch_GetExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperienceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodSearchServer).GetExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goodsearch.GoodSearch/GetExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodSearchServer).GetExperience(ctx, req.(*GetExperienceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoodSearch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goodsearch.GoodSearch",
	HandlerType: (*GoodSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExperience",
			Handler:    _GoodSearch_GetExperience_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goodsearch.proto",
}
