// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goodsearch.proto

package goodsearch

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_SUCCESS Status = 0
	Status_FAILURE Status = 1
)

var Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{0}
}

type GetExperienceReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExperienceReq) Reset()         { *m = GetExperienceReq{} }
func (m *GetExperienceReq) String() string { return proto.CompactTextString(m) }
func (*GetExperienceReq) ProtoMessage()    {}
func (*GetExperienceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{0}
}

func (m *GetExperienceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExperienceReq.Unmarshal(m, b)
}
func (m *GetExperienceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExperienceReq.Marshal(b, m, deterministic)
}
func (m *GetExperienceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExperienceReq.Merge(m, src)
}
func (m *GetExperienceReq) XXX_Size() int {
	return xxx_messageInfo_GetExperienceReq.Size(m)
}
func (m *GetExperienceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExperienceReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetExperienceReq proto.InternalMessageInfo

func (m *GetExperienceReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetExperienceResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExperienceResp) Reset()         { *m = GetExperienceResp{} }
func (m *GetExperienceResp) String() string { return proto.CompactTextString(m) }
func (*GetExperienceResp) ProtoMessage()    {}
func (*GetExperienceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{1}
}

func (m *GetExperienceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExperienceResp.Unmarshal(m, b)
}
func (m *GetExperienceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExperienceResp.Marshal(b, m, deterministic)
}
func (m *GetExperienceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExperienceResp.Merge(m, src)
}
func (m *GetExperienceResp) XXX_Size() int {
	return xxx_messageInfo_GetExperienceResp.Size(m)
}
func (m *GetExperienceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExperienceResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetExperienceResp proto.InternalMessageInfo

func (m *GetExperienceResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetExperienceResp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type UpdateExperienceReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateExperienceReq) Reset()         { *m = UpdateExperienceReq{} }
func (m *UpdateExperienceReq) String() string { return proto.CompactTextString(m) }
func (*UpdateExperienceReq) ProtoMessage()    {}
func (*UpdateExperienceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{2}
}

func (m *UpdateExperienceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateExperienceReq.Unmarshal(m, b)
}
func (m *UpdateExperienceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateExperienceReq.Marshal(b, m, deterministic)
}
func (m *UpdateExperienceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateExperienceReq.Merge(m, src)
}
func (m *UpdateExperienceReq) XXX_Size() int {
	return xxx_messageInfo_UpdateExperienceReq.Size(m)
}
func (m *UpdateExperienceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateExperienceReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateExperienceReq proto.InternalMessageInfo

func (m *UpdateExperienceReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateExperienceResp struct {
	Status               Status             `protobuf:"varint,1,opt,name=status,proto3,enum=goodsearch.Status" json:"status,omitempty"`
	Experience           *ExperiencePayload `protobuf:"bytes,2,opt,name=experience,proto3" json:"experience,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateExperienceResp) Reset()         { *m = UpdateExperienceResp{} }
func (m *UpdateExperienceResp) String() string { return proto.CompactTextString(m) }
func (*UpdateExperienceResp) ProtoMessage()    {}
func (*UpdateExperienceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{3}
}

func (m *UpdateExperienceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateExperienceResp.Unmarshal(m, b)
}
func (m *UpdateExperienceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateExperienceResp.Marshal(b, m, deterministic)
}
func (m *UpdateExperienceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateExperienceResp.Merge(m, src)
}
func (m *UpdateExperienceResp) XXX_Size() int {
	return xxx_messageInfo_UpdateExperienceResp.Size(m)
}
func (m *UpdateExperienceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateExperienceResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateExperienceResp proto.InternalMessageInfo

func (m *UpdateExperienceResp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_SUCCESS
}

func (m *UpdateExperienceResp) GetExperience() *ExperiencePayload {
	if m != nil {
		return m.Experience
	}
	return nil
}

type ExperiencePayload struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExperiencePayload) Reset()         { *m = ExperiencePayload{} }
func (m *ExperiencePayload) String() string { return proto.CompactTextString(m) }
func (*ExperiencePayload) ProtoMessage()    {}
func (*ExperiencePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{4}
}

func (m *ExperiencePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperiencePayload.Unmarshal(m, b)
}
func (m *ExperiencePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperiencePayload.Marshal(b, m, deterministic)
}
func (m *ExperiencePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperiencePayload.Merge(m, src)
}
func (m *ExperiencePayload) XXX_Size() int {
	return xxx_messageInfo_ExperiencePayload.Size(m)
}
func (m *ExperiencePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperiencePayload.DiscardUnknown(m)
}

var xxx_messageInfo_ExperiencePayload proto.InternalMessageInfo

func (m *ExperiencePayload) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type IndexAllExperiencesReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexAllExperiencesReq) Reset()         { *m = IndexAllExperiencesReq{} }
func (m *IndexAllExperiencesReq) String() string { return proto.CompactTextString(m) }
func (*IndexAllExperiencesReq) ProtoMessage()    {}
func (*IndexAllExperiencesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{5}
}

func (m *IndexAllExperiencesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexAllExperiencesReq.Unmarshal(m, b)
}
func (m *IndexAllExperiencesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexAllExperiencesReq.Marshal(b, m, deterministic)
}
func (m *IndexAllExperiencesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexAllExperiencesReq.Merge(m, src)
}
func (m *IndexAllExperiencesReq) XXX_Size() int {
	return xxx_messageInfo_IndexAllExperiencesReq.Size(m)
}
func (m *IndexAllExperiencesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexAllExperiencesReq.DiscardUnknown(m)
}

var xxx_messageInfo_IndexAllExperiencesReq proto.InternalMessageInfo

type IndexAllExperiencesResp struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=goodsearch.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexAllExperiencesResp) Reset()         { *m = IndexAllExperiencesResp{} }
func (m *IndexAllExperiencesResp) String() string { return proto.CompactTextString(m) }
func (*IndexAllExperiencesResp) ProtoMessage()    {}
func (*IndexAllExperiencesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44eebf31dd75a2c, []int{6}
}

func (m *IndexAllExperiencesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexAllExperiencesResp.Unmarshal(m, b)
}
func (m *IndexAllExperiencesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexAllExperiencesResp.Marshal(b, m, deterministic)
}
func (m *IndexAllExperiencesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexAllExperiencesResp.Merge(m, src)
}
func (m *IndexAllExperiencesResp) XXX_Size() int {
	return xxx_messageInfo_IndexAllExperiencesResp.Size(m)
}
func (m *IndexAllExperiencesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexAllExperiencesResp.DiscardUnknown(m)
}

var xxx_messageInfo_IndexAllExperiencesResp proto.InternalMessageInfo

func (m *IndexAllExperiencesResp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_SUCCESS
}

func init() {
	proto.RegisterEnum("goodsearch.Status", Status_name, Status_value)
	proto.RegisterType((*GetExperienceReq)(nil), "goodsearch.GetExperienceReq")
	proto.RegisterType((*GetExperienceResp)(nil), "goodsearch.GetExperienceResp")
	proto.RegisterType((*UpdateExperienceReq)(nil), "goodsearch.UpdateExperienceReq")
	proto.RegisterType((*UpdateExperienceResp)(nil), "goodsearch.UpdateExperienceResp")
	proto.RegisterType((*ExperiencePayload)(nil), "goodsearch.ExperiencePayload")
	proto.RegisterType((*IndexAllExperiencesReq)(nil), "goodsearch.IndexAllExperiencesReq")
	proto.RegisterType((*IndexAllExperiencesResp)(nil), "goodsearch.IndexAllExperiencesResp")
}

func init() { proto.RegisterFile("goodsearch.proto", fileDescriptor_a44eebf31dd75a2c) }

var fileDescriptor_a44eebf31dd75a2c = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0x09, 0x7f, 0x22, 0x4e, 0xb1, 0xa4, 0x53, 0xd1, 0x10, 0x2c, 0x96, 0x15, 0x51,
	0x7a, 0xe8, 0x21, 0x1e, 0x3c, 0x79, 0x28, 0x25, 0x96, 0x42, 0x0f, 0xb2, 0x21, 0x57, 0x21, 0x76,
	0x17, 0x0d, 0x84, 0xee, 0x36, 0xbb, 0x42, 0x7b, 0xf4, 0x23, 0xf8, 0x8d, 0xc5, 0x55, 0x9a, 0x35,
	0x0d, 0x11, 0x6f, 0xc9, 0xcc, 0xef, 0x3d, 0xf2, 0xe6, 0x05, 0xfc, 0x67, 0x21, 0x98, 0xe2, 0x59,
	0xb9, 0x7c, 0x19, 0xcb, 0x52, 0x68, 0x81, 0x50, 0x4d, 0x08, 0x01, 0x7f, 0xc6, 0x75, 0xbc, 0x91,
	0xbc, 0xcc, 0xf9, 0x6a, 0xc9, 0x29, 0x5f, 0x63, 0x17, 0xdc, 0x9c, 0x05, 0xce, 0xd0, 0xb9, 0x3e,
	0xa4, 0x6e, 0xce, 0xc8, 0x2d, 0xf4, 0x6a, 0x8c, 0x92, 0x75, 0x08, 0x11, 0xfe, 0xeb, 0xad, 0xe4,
	0x81, 0x6b, 0x26, 0xe6, 0x99, 0x5c, 0x42, 0x3f, 0x95, 0x2c, 0xd3, 0xbc, 0xdd, 0xff, 0xcd, 0x81,
	0xe3, 0x7d, 0x4e, 0x49, 0x1c, 0x81, 0xa7, 0x74, 0xa6, 0x5f, 0x95, 0x81, 0xbb, 0x11, 0x8e, 0xad,
	0x2c, 0x89, 0xd9, 0xd0, 0x6f, 0x02, 0xef, 0x00, 0xf8, 0x4e, 0x6d, 0xbe, 0xa2, 0x13, 0x0d, 0x6c,
	0xbe, 0xf2, 0x7e, 0xc8, 0xb6, 0x85, 0xc8, 0x18, 0xb5, 0x04, 0xe4, 0x0a, 0x7a, 0x7b, 0xc0, 0x2e,
	0x93, 0x63, 0x65, 0x0a, 0xe0, 0x64, 0xbe, 0x62, 0x7c, 0x33, 0x29, 0x8a, 0x4a, 0xa0, 0x28, 0x5f,
	0x93, 0x18, 0x4e, 0x1b, 0x37, 0x7f, 0x0b, 0x32, 0x22, 0xe0, 0x7d, 0x4d, 0xb0, 0x03, 0x07, 0x49,
	0x3a, 0x9d, 0xc6, 0x49, 0xe2, 0xff, 0xfb, 0x7c, 0xb9, 0x9f, 0xcc, 0x17, 0x29, 0x8d, 0x7d, 0x27,
	0x7a, 0x77, 0x01, 0x66, 0x42, 0xb0, 0xc4, 0x38, 0xe0, 0x02, 0x8e, 0x7e, 0x14, 0x84, 0x67, 0xb6,
	0x7f, 0xbd, 0xdf, 0x70, 0xd0, 0xb2, 0x55, 0x12, 0x53, 0xf0, 0xeb, 0x6d, 0xe0, 0xb9, 0x2d, 0x69,
	0xe8, 0x34, 0x1c, 0xb6, 0x03, 0x4a, 0xe2, 0x23, 0xf4, 0x1b, 0xce, 0x83, 0xc4, 0x16, 0x36, 0x5f,
	0x36, 0xbc, 0xf8, 0x95, 0x51, 0xf2, 0xc9, 0x33, 0x3f, 0xf7, 0xcd, 0x47, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x43, 0x44, 0xb2, 0x3c, 0xf0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoodSearchClient is the client API for GoodSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoodSearchClient interface {
	GetExperience(ctx context.Context, in *GetExperienceReq, opts ...grpc.CallOption) (*GetExperienceResp, error)
	UpdateExperience(ctx context.Context, in *UpdateExperienceReq, opts ...grpc.CallOption) (*UpdateExperienceResp, error)
	IndexAllExperiences(ctx context.Context, in *IndexAllExperiencesReq, opts ...grpc.CallOption) (*IndexAllExperiencesResp, error)
}

type goodSearchClient struct {
	cc *grpc.ClientConn
}

func NewGoodSearchClient(cc *grpc.ClientConn) GoodSearchClient {
	return &goodSearchClient{cc}
}

func (c *goodSearchClient) GetExperience(ctx context.Context, in *GetExperienceReq, opts ...grpc.CallOption) (*GetExperienceResp, error) {
	out := new(GetExperienceResp)
	err := c.cc.Invoke(ctx, "/goodsearch.GoodSearch/GetExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodSearchClient) UpdateExperience(ctx context.Context, in *UpdateExperienceReq, opts ...grpc.CallOption) (*UpdateExperienceResp, error) {
	out := new(UpdateExperienceResp)
	err := c.cc.Invoke(ctx, "/goodsearch.GoodSearch/UpdateExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodSearchClient) IndexAllExperiences(ctx context.Context, in *IndexAllExperiencesReq, opts ...grpc.CallOption) (*IndexAllExperiencesResp, error) {
	out := new(IndexAllExperiencesResp)
	err := c.cc.Invoke(ctx, "/goodsearch.GoodSearch/IndexAllExperiences", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodSearchServer is the server API for GoodSearch service.
type GoodSearchServer interface {
	GetExperience(context.Context, *GetExperienceReq) (*GetExperienceResp, error)
	UpdateExperience(context.Context, *UpdateExperienceReq) (*UpdateExperienceResp, error)
	IndexAllExperiences(context.Context, *IndexAllExperiencesReq) (*IndexAllExperiencesResp, error)
}

// UnimplementedGoodSearchServer can be embedded to have forward compatible implementations.
type UnimplementedGoodSearchServer struct {
}

func (*UnimplementedGoodSearchServer) GetExperience(ctx context.Context, req *GetExperienceReq) (*GetExperienceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExperience not implemented")
}
func (*UnimplementedGoodSearchServer) UpdateExperience(ctx context.Context, req *UpdateExperienceReq) (*UpdateExperienceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExperience not implemented")
}
func (*UnimplementedGoodSearchServer) IndexAllExperiences(ctx context.Context, req *IndexAllExperiencesReq) (*IndexAllExperiencesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexAllExperiences not implemented")
}

func RegisterGoodSearchServer(s *grpc.Server, srv GoodSearchServer) {
	s.RegisterService(&_GoodSearch_serviceDesc, srv)
}

func _GoodSearch_GetExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperienceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodSearchServer).GetExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goodsearch.GoodSearch/GetExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodSearchServer).GetExperience(ctx, req.(*GetExperienceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodSearch_UpdateExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExperienceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodSearchServer).UpdateExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goodsearch.GoodSearch/UpdateExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodSearchServer).UpdateExperience(ctx, req.(*UpdateExperienceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodSearch_IndexAllExperiences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexAllExperiencesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodSearchServer).IndexAllExperiences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goodsearch.GoodSearch/IndexAllExperiences",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodSearchServer).IndexAllExperiences(ctx, req.(*IndexAllExperiencesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoodSearch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goodsearch.GoodSearch",
	HandlerType: (*GoodSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExperience",
			Handler:    _GoodSearch_GetExperience_Handler,
		},
		{
			MethodName: "UpdateExperience",
			Handler:    _GoodSearch_UpdateExperience_Handler,
		},
		{
			MethodName: "IndexAllExperiences",
			Handler:    _GoodSearch_IndexAllExperiences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goodsearch.proto",
}
